# Generated by Django 4.0.5 on 2022-06-07 11:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='cell_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('STORE', 'STORE'), ('CUSTOMER', 'CUSTOMER')], default=users.models.UserRoleEnum['CUSTOMER'], max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=12, null=True),
        ),
    ]
