# Generated by Django 4.0.5 on 2022-06-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('STORE', 'STORE'), ('CUSTOMER', 'CUSTOMER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('STORE', 'STORE'), ('CUSTOMER', 'CUSTOMER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='role',
            field=models.CharField(choices=[('STORE', 'STORE'), ('CUSTOMER', 'CUSTOMER')], max_length=20),
        ),
    ]
