# Generated by Django 4.0.5 on 2022-06-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_store_brand_name_store_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('STORE', 'STORE'), ('CUSTOMER', 'CUSTOMER')], max_length=20, null=True),
        ),
    ]
