# Generated by Django 4.0.5 on 2022-06-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
        migrations.RemoveField(
            model_name='store',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
