# Generated by Django 4.0.4 on 2022-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField(max_length=10)),
                ('product_url', models.URLField()),
                ('image_url', models.URLField()),
                ('category', models.CharField(choices=[('Formal Shirts', 'Formal Shirts'), ('Casual Shirts', 'Casual Shirts'), ('Dress Pants', 'Dress Pants')], max_length=100)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Suspended', 'Suspended')], default='Suspended', max_length=20)),
                ('discount', models.FloatField(blank=True, max_length=2, null=True)),
                ('quantity', models.FloatField(max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clicks', models.FloatField()),
                ('quantity', models.FloatField()),
            ],
        ),
    ]
