# Generated by Django 4.0.5 on 2022-06-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_history', to='users.customer'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='api.product'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='api.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.store'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_customers', to='users.customer'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_products', to='api.product'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasehistory',
            unique_together={('product', 'customer')},
        ),
    ]
