# Generated by Django 4.0.4 on 2022-05-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_products', to='users.customer')),
                ('prodcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_customers', to='api.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
