# Generated by Django 4.0.5 on 2022-06-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_products_productcharacteristics_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
