# Generated by Django 4.0.4 on 2022-05-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('api', '0004_remove_productcharacteristics_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductHistory',
            new_name='PurchaseHistory',
        ),
    ]
